defaults:
  - material: diffuse_0.3
  - sensor: SPAD
  - hydra
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: basic

exp_name: ${pbrt.scene}
seed: 0
device: cpu
display_server: localhost:14158

projector:
  pattern: ConventionalGray
  index: 12

pbrt:
  executable: pbrt
  scene: dragon_subsurface
  type: "meas" # use "gt" for groundtruth
  save_dump: False

output:
  name: output
  extension: exr

reconstruct:
  num_codes: 10
  include_inverse: True
  include_all_white: True # 0th capture as all white

visualize:
  show_correspondences: False
  show_abs_error: True



