defaults:
  - material: diffuse
  - hydra
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - hydra/launcher: joblib

exp_name: ${pbrt.scene}
seed: 0
device: cpu
display_server: localhost:14158

projector:
  pattern: ConventionalGray
  index: 12

pbrt:
  executable: /Users/varun/Dev/pbrt-v4/build/pbrt
  scene: dragon_subsurface
  type: "meas" # use "gt" for groundtruth
  save_dump: false

output:
  name: output



